version: '3'
services:
    discovery:
        image: eureka-server:latest
        ports:
            - 8761:8761
    client:
        image: eureka-client:latest
        environment:
            - JAVA_OPTS=
              -Deureka.client.service-url.defaultZone = http://admin:pwd@discovery:8761/eureka
        depends_on:
            - discovery
        ports:
            - 8101:8101
