server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuonglv/springcloud-config.git
          # username: kuonglv
          # password: 123456
          clone-on-start: true
        label: master
eureka:
  client:
    service-url:
      defaultZone: http://admin:pwd@localhost:8761/eureka/
